# Generated by Django 3.1.4 on 2021-04-19 02:03

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('proprietor', models.CharField(blank=True, choices=[('public', 'GOVERNMENT OWNED'), ('private', 'PRIVATE OWNED')], max_length=10, null=True)),
                ('operation_hours', models.CharField(blank=True, choices=[('full_time', 'FULL TIME (24 HOURS)'), ('part_time_day', 'DAY HOURS'), ('part_time_night', 'NIGHT HOURS')], max_length=20, null=True)),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home_address', 'HOME ADDRESS'), ('work_address', 'WORK ADDRESS')], max_length=20)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
