# Generated by Django 3.1.4 on 2021-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
