# Generated by Django 3.1.4 on 2021-04-20 15:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_carpark_available_slots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialaddress',
            options={'verbose_name': 'special address', 'verbose_name_plural': 'special addresses'},
        ),
        migrations.AddField(
            model_name='carpark',
            name='carpark_centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
