# Generated by Django 3.1.4 on 2021-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_auto_20210420_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='available_slots',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='operation_hours',
            field=models.CharField(choices=[('full_time', 'FULL TIME (24 HOURS)'), ('part_time_day', 'DAY HOURS'), ('part_time_night', 'NIGHT HOURS')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='price',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='proprietor',
            field=models.CharField(choices=[('public', 'GOVERNMENT OWNED'), ('private', 'PRIVATE OWNED')], default='private', max_length=10),
        ),
    ]
