# Generated by Django 3.1.4 on 2021-04-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_auto_20210421_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialaddress',
            name='user',
        ),
    ]
