# Generated by Django 3.1.4 on 2021-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_remove_specialaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='operation_hours',
            field=models.CharField(blank=True, choices=[('full_time', 'FULL TIME (24 HOURS)'), ('part_time_day', 'DAY HOURS'), ('part_time_night', 'NIGHT HOURS')], default='full_time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='proprietor',
            field=models.CharField(blank=True, choices=[('public', 'GOVERNMENT OWNED'), ('private', 'PRIVATE OWNED')], default='private', max_length=10, null=True),
        ),
    ]
